version: '3.8'

services:
  tfm-hook:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Mount Docker socket to allow container to restart other services
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount git repositories (adjust paths as needed)
      - /path/to/repos:/repos:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s